// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";

interface RegistryEntry {
  name: string;
  type: "registry:example" | "registry:config";
  registryDependencies: string[];
  files: string[];
  component: React.LazyExoticComponent<React.ComponentType<unknown>>;
  source: string;
  category: string;
  subcategory: string;
  chunks: string[]; // Assuming chunks contains string identifiers
}
export const Index: Record<string, Record<string, RegistryEntry>> = {
  default: {
    spotlight: {
      name: "spotlight",
      type: "registry:example",
      registryDependencies: ["spotlight"],
      files: ["src/registry/smooth-ui/spotlight.tsx"],
      component: React.lazy(() => import("@/registry/smooth-ui/spotlight.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: [],
    },
    "spotlight-talwindcss.config": {
      name: "spotlight-talwindcss.config",
      type: "registry:config",
      registryDependencies: ["spotlight-talwindcss.config"],
      files: ["src/registry/config/spotlight-talwindcss.config.ts"],
      component: React.lazy(
        () => import("@/registry/config/spotlight-talwindcss.config.ts")
      ),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: [],
    },
    "spotlight-demo": {
      name: "spotlight",
      type: "registry:example",
      registryDependencies: ["spotlight"],
      files: ["src/registry/example/spotlight-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/example/spotlight-demo.tsx")
      ),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: [],
    },
    "spotlight-card": {
      name: "spotlight-card",
      type: "registry:example",
      registryDependencies: ["spotlight-card"],
      files: ["src/registry/smooth-ui/spotlight-card.tsx"],
      component: React.lazy(
        () => import("@/registry/smooth-ui/spotlight-card.tsx")
      ),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: [],
    },
    "spotlight-card-demo": {
      name: "spotlight-card",
      type: "registry:example",
      registryDependencies: ["spotlight-card"],
      files: ["src/registry/example/spotlight-card-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/example/spotlight-card-demo.tsx")
      ),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: [],
    },
    "spotlight-custom-color": {
      name: "spotlight-custom-color",
      type: "registry:example",
      registryDependencies: ["spotlight-card"],
      files: ["src/registry/example/spotlight-custom-color.tsx"],
      component: React.lazy(
        () => import("@/registry/example/spotlight-custom-color.tsx")
      ),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: [],
    },
    "spotlight-card-border": {
      name: "spotlight-card-border",
      type: "registry:example",
      registryDependencies: ["spotlight-card"],
      files: ["src/registry/example/spotlight-card-border.tsx"],
      component: React.lazy(
        () => import("@/registry/example/spotlight-card-border.tsx")
      ),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: [],
    },
    "spotlight-card-highlight": {
      name: "spotlight-card-highlight",
      type: "registry:example",
      registryDependencies: ["spotlight-card"],
      files: ["src/registry/example/spotlight-card-highlight.tsx"],
      component: React.lazy(
        () => import("@/registry/example/spotlight-card-highlight.tsx")
      ),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: [],
    },
    "card-pulse-border-talwindcss.config": {
      name: "card-pulse-border-talwindcss.config",
      type: "registry:config",
      registryDependencies: ["card-pulse-border-talwindcss.config"],
      files: ["src/registry/config/card-pulse-border-talwindcss.config.ts"],
      component: React.lazy(
        () => import("@/registry/config/card-pulse-border-talwindcss.config.ts")
      ),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: [],
    },
    "card-pulse-border": {
      name: "card-pulse-border",
      type: "registry:example",
      registryDependencies: ["card-pulse-border"],
      files: ["src/registry/smooth-ui/card-pulse-border.tsx"],
      component: React.lazy(
        () => import("@/registry/smooth-ui/card-pulse-border.tsx")
      ),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: [],
    },
    "card-pulse-border-demo": {
      name: "card-pulse-border-demo",
      type: "registry:example",
      registryDependencies: ["card-pulse-border"],
      files: ["src/registry/example/card-pulse-border-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/example/card-pulse-border-demo.tsx")
      ),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: [],
    },
    "upgrade-to-pro-demo": {
      name: "upgrade-to-pro-demo",
      type: "registry:example",
      registryDependencies: ["upgrade-to-pro"],
      files: ["src/registry/example/upgrade-to-pro-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/example/upgrade-to-pro-demo.tsx")
      ),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: [],
    },
    "limited-counter-demo": {
      name: "limited-counter-demo",
      type: "registry:example",
      registryDependencies: ["limited-counter"],
      files: ["src/registry/example/limited-counter-demo.tsx"],
      component: React.lazy(
        () => import("@/registry/example/limited-counter-demo.tsx")
      ),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: [],
    },
  },
};
